# Generated by Django 5.2.1 on 2025-05-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regalo',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='regali/'),
        ),
    ]
