# Generated by Django 5.2.1 on 2025-05-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_regalo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='regalo',
            name='modello',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
