# Generated by Django 5.2.1 on 2025-05-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0004_regalo_modello'),
    ]

    operations = [
        migrations.AddField(
            model_name='regalo',
            name='prezzo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
