# Generated by Django 5.2.1 on 2025-05-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0005_regalo_prezzo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostazioniPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(default='Lista Nascita', max_length=200)),
                ('messaggio', models.TextField(blank=True)),
            ],
        ),
    ]
