# Generated by Django 5.2.1 on 2025-05-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0006_impostazionipagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='regalo',
            name='ordine_default',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
