# Generated by Django 5.2.1 on 2025-05-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0007_regalo_ordine_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regalo',
            name='modello',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
