# Generated by Django 5.2.1 on 2025-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0008_alter_regalo_modello'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtenteRegistrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_registrazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
