# Generated by Django 5.2.1 on 2025-05-10 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0009_utenteregistrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='regalo',
            name='prenotato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lista.utenteregistrato'),
        ),
    ]
