# Generated by Django 5.2.1 on 2025-05-11 15:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0010_regalo_prenotato_da'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impostazionipagina',
            name='messaggio',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
